---
kind: ConfigMap
apiVersion: v1
metadata:
  name: pulsar-consumer-config
  namespace: pulsar-client
data:
  pulsar_url: "pulsar://10.0.0.36:6650"
  topic: "my-topic"
  subscription_name: "my-subscription1"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-consumer
  namespace: pulsar-client
spec:
  selector:
    matchLabels:
      app: my-consumer
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-consumer
    spec:
      containers:
        - name: pulsar-consumer
          image: yuwsung1/pulsar-python-consumer:v0.1
          imagePullPolicy: Always
          tty: true
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          env:
            - name: PULSAR_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsar-consumer-config
                  key: pulsar_url
            - name: PULSAR_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: pulsar-consumer-config
                  key: topic
            - name: PULSAR_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: pulsar-consumer-config
                  key: subscription_name